/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.awt.Color;
import java.awt.Font;
import java.io.*;
import java.net.Socket;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ProgressMonitorInputStream;
import javax.swing.SwingWorker;

/**
 *
 * @author ASUS
 */
public class UploadFile extends javax.swing.JFrame {

    private Socket client;
    private String fileName;
    private DataOutputStream dos;
    private DataInputStream dis;
    private String currPath;
    private File fileToSend;
    private int BUFFER_SIZE = 100;

    /**
     * Creates new form SendFile
     */
    public UploadFile(Socket client) {
        this.client = client;
        try {
            dos = new DataOutputStream(client.getOutputStream());
            dis = new DataInputStream(client.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(UploadFile.class.getName()).log(Level.SEVERE, null, ex);
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pathInput = new javax.swing.JTextField();
        pathInput.setEditable(false);
        chooseFileBtn = new javax.swing.JButton();
        confirmBtn = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jLabel1.setText("Tập tin để tải lên:");

        pathInput.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        pathInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathInputActionPerformed(evt);
            }
        });

        chooseFileBtn.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        chooseFileBtn.setText("Chọn...");
        chooseFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFileBtnActionPerformed(evt);
            }
        });

        confirmBtn.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        confirmBtn.setText("Tải lên");
        confirmBtn.setPreferredSize(new java.awt.Dimension(100, 29));
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        progressBar.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        progressBar.setStringPainted(true);
        progressBar.setForeground(Color.BLUE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pathInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseFileBtn))
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 305, Short.MAX_VALUE)
                        .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 305, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseFileBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pathInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathInputActionPerformed

    private void chooseFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFileBtnActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new java.io.File("."));
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnVal = fc.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            fileToSend = fc.getSelectedFile();
            currPath = fileToSend.getAbsolutePath();
            pathInput.setText(currPath);
            try {
                dos.writeUTF("UPLOAD_FILE_REQUEST;" + fileToSend.getName() + ";" + fileToSend.length());
            } catch (IOException ex) {
                Logger.getLogger(UploadFile.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_chooseFileBtnActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        try {
//            String path = currPath + "\\" + fileName;
            if (pathInput.getText().equals("")) {
                new MyOptionPane("Xin chọn một tập tin", this).showMessageDialog("Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (new MyOptionPane("Bạn chắc chắn muốn tải lên " + currPath + "?", this).showConfirmDialog("Bạn chắc chứ", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) {
                return;
            }
            progressBar.setVisible(true);
            String command = dis.readUTF();
            switch (command) {
                case "UPLOAD_FILE_ACCEPTED":
                    new UploadFileTask(fileToSend).execute();
                    break;
            }

        } catch (IOException ex) {
            ex.printStackTrace();
        }
//            try {
////            String path = currPath + "\\" + fileName;
//            if (pathInput.getText().equals("")) {
//                new MyOptionPane("Xin chọn một tập tin", this).showMessageDialog("Lỗi", JOptionPane.ERROR_MESSAGE);
//                return;
//            } else {
//                if(currPath==""){
//                    currPath2=pathInput.getText();    
//                    if (new MyOptionPane("Bạn chắc chắn muốn tải lên " + currPath2 + "?", this).showConfirmDialog("Bạn chắc chứ", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) {
//                    return;
//                }
//                }else{
//                    if (new MyOptionPane("Bạn chắc chắn muốn tải lên " + currPath + "?", this).showConfirmDialog("Bạn chắc chứ", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) {
//                        return;
//                    }
//                }
//            }
//            progressBar.setVisible(true);
//            File f=new File(currPath2);   
//            if(currPath==""){               
//                try {
//                    dos.writeUTF("UPLOAD_FILE_REQUEST;" + f.getName() + ";" + f.length());
//                } catch (IOException ex) {
//                    Logger.getLogger(UploadFile.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//            String command = dis.readUTF();
//            switch (command) {
//                case "UPLOAD_FILE_ACCEPTED":   
//                    if(currPath==""){
//                        new UploadFileTask(f).execute();
//                        break;
//                    }else{
//                        new UploadFileTask(fileToSend).execute();
//                        break;
//                    }
//                    
//            }
//
//        } catch (IOException ex) {
//            ex.printStackTrace();
//        }
    }//GEN-LAST:event_confirmBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseFileBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField pathInput;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

    class UploadFileTask extends SwingWorker<Void, Integer> {

        File fileToSend;
        long fileLen;
        InputStream input;
        long totalRead = 0;
        byte[] buffer = new byte[BUFFER_SIZE];
        int count = 0;

        public UploadFileTask(File fileToSend) {
            this.fileToSend = fileToSend;
            fileLen = fileToSend.length();
            try {
                dos.writeUTF("UPLOAD_FILE_BEGIN;" + fileToSend.getName() + ";" + fileLen);
                input = new FileInputStream(fileToSend);
            } catch (IOException ex) {
                Logger.getLogger(UploadFile.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        @Override
        protected Void doInBackground() throws Exception {
            confirmBtn.setEnabled(false);
            confirmBtn.setText("Đang tải lên...");
            chooseFileBtn.setEnabled(false);
            while (totalRead != fileLen) {
                count = input.read(buffer);
                dos.writeInt(count);
                dos.write(buffer, 0, count);
                totalRead += (long) count;
                int p = (int) (((float) totalRead / (float) fileLen) * 100f);
                publish(p);
            }
            return null;
        }

        @Override
        protected void process(List<Integer> chunks) {
            progressBar.setValue(chunks.get(chunks.size()-1));
        }

        @Override
        protected void done() {
            try {
                dos.flush();
            } catch (IOException ex) {
                Logger.getLogger(UploadFile.class.getName()).log(Level.SEVERE, null, ex);
            }
            new MyOptionPane("Tải lên thành công!", UploadFile.this).showMessageDialog("Tải lên thành công", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }

    }
}
